language: node_js
node_js:
- 8.11.3
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
- yarn run lint
- yarn run build
- yarn run test-scores
after_success:
- git clone ${GIT_URL}
- mv build projects/steganography-toolkit
- cd projects
- git add steganography-toolkit
- git commit --allow-empty-message -m ''
- git push origin master
