language: node_js
node_js:
- 8.11.3
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
    secure: D9GaZwse3Li+U04puSosCB9hIBCKLlQtYx9CplUIEv+BbUR72IH7puDgKrEhN7Q0XikuQH+Qc0maWt+0ui7R76xB5BtjWoR9PoI+z7vL+bS4rQa334XVzPF8v74k0/Iq7v3EL7pUp7jKxegePdyMK2aC05PXgnAeMrslNIj48eWdXaMIzd4NEumTZZckbJhSbSCq8vxaQyHsbzjI3L9FydixImZIaGrqKNqcVhDSZFrVQZO4c35wj6N/I6RzfG5kfhqgkIFtIuE8sPx6qPlT2ZziX5LYZFelvMGKaeinRfkssGJBeFoo5JMhciogoAIUitwfd3+GrICoBcz7HZF8YmAgz4XghXZyJlMTqkY+g/tDXWTLY0XXDh+OLVO7SH++LPMiWmBmoy6Qa5PU2XU1X6qodq30KQXvPjRmOknJH4i1mtCU09gR3FzX2N0XjBy2cJUD5Nrsdi+BZeVejldF1OST718DgtNebHLF3l2WjxLGLXd7552YOli5ZgWZUMaeUUiLmT8jwOFyGq1v1N8mS7frdzQcl/9PZTeCIt+8FLSkLMFlOYQ+IKgflVF/FmZJMHy2dANn7sc8TXQCHY5xRb4xv3+GMH/McOZwidQvqpiR9BtO0eDkBi+eS8fzZEPTqTo5+ubK0u6OIT4zwMOrW0SeDyDeAkmsNSXmPuoyC04=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
- yarn run lint
- yarn run build
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- cd build
- find **/* -type f -exec curl --ftp-create-dirs -T {} ${SFTP_URL} \;
