name: Deploy
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        run: |
          yarn firebase use --add steganography-toolkit
          yarn firebase deploy --token "$FIREBASE_TOKEN" --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
